<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-PortalBlazor-E48696EB-F7E9-4804-A0ED-1A40C9B7FAFB</UserSecretsId>
        <RootNamespace>PortalBlazor</RootNamespace>
        <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <Platform>x64</Platform>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="12.0.1" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
        <PackageReference Include="Blazor.Bootstrap" Version="3.5.0" />
        <PackageReference Include="Blazor.Flags" Version="1.0.0.1" />
        <PackageReference Include="Blazored.Modal" Version="7.3.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.6"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6"/>
        <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="2.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Configuration.Core\Configuration.Core.csproj" />
      <ProjectReference Include="..\Data\Data.csproj" />
      <ProjectReference Include="..\Notifications.Core\Notifications.Core.csproj" />
      <ProjectReference Include="..\Resources\Resources.csproj" />
      <ProjectReference Include="..\Users.Core\Users.Core.csproj" />
      <ProjectReference Include="..\ViewModels\ViewModels.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Data\app.db">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </None>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\lib\bower.json" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\index-svg.html" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\index.html" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\index.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\LICENSE" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\qrcode.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\qrcode.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\README.md" />
    </ItemGroup>

</Project>
