<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.6"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Configuration.Shared\Configuration.Shared.csproj" />
      <ProjectReference Include="..\Users.Core\Users.Core.csproj" />
    </ItemGroup>

</Project>
