<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Blazor.Bootstrap" Version="3.3.1" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6"/>
    </ItemGroup>
    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Identity">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.6\Microsoft.AspNetCore.Identity.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Mvc.Abstractions">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.6\Microsoft.AspNetCore.Mvc.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Identity">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.6\Microsoft.AspNetCore.Identity.dll</HintPath>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Abstract\Abstract.csproj" />
    </ItemGroup>

</Project>
