<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Event-Saver-E48696EB-F7E9-4804-A0ED-1A40C9B7FAFB</UserSecretsId>
        <RootNamespace>Event-Saver</RootNamespace>
        <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazor.Bootstrap" Version="3.3.1" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.6"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Data\Data.csproj" />
      <ProjectReference Include="..\Users\Users.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Users\Users.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Data\app.db">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </None>
    </ItemGroup>

</Project>
